In [6]:
import numpy as np
import pandas as pd
import statsmodels.api as sm

df = pd.read_csv('21年6月实时数据NJ-S122其林门_train.csv')
df['volume'] = df[['XKC', 'DKC', 'XHC', 'ZHC', 'DHC', 'TDH']].sum(axis=1)
df = df[(df['volume']>0) & (df['PJCTJJ']>0) & (df['SJZYL']>0)]
df.head()

,YEAR,GCRQ,GCZBS,HOUR,MINUTE,CDH,XSFX,SBSBM,DCSJLX,SJXH,...,OFF_MINS,ERR_CODE,ERR_DESC,DELETE_BY,DELETE_TIME,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME,volume
0,2021,24-JUN-21,32000020160926C5B281FC540615BAA6,20,10,33,X,141150316092101,0,231,...,-2.0,NaN,NaN,NaN,NaN,sys,24-JUN-21 07.13.02.757000000 PM,sys,24-JUN-21 07.09.41.672042000 PM,22
1,2021,05-JUN-21,32000020160926C5B281FC540615BAA6,18,0,13,S,141150316092101,0,205,...,-2.1,NaN,NaN,NaN,NaN,sys,05-JUN-21 05.02.57.974000000 PM,sys,05-JUN-21 05.00.32.536633000 PM,38
3,2021,27-JUN-21,32000020160926C5B281FC540615BAA6,6,45,36,X,141150316092101,0,70,...,1.1,NaN,NaN,NaN,NaN,sys,27-JUN-21 05.51.09.066000000 AM,sys,27-JUN-21 05.47.28.190581000 AM,4
4,2021,17-JUN-21,32000020160926C5B281FC540615BAA6,8,40,12,S,141150316092101,0,93,...,2.3,NaN,NaN,NaN,NaN,sys,17-JUN-21 07.47.19.126000000 AM,sys,17-JUN-21 07.58.02.013440000 AM,77
5,2021,04-JUN-21,32000020160926C5B281FC540615BAA6,14,5,12,S,141150316092101,0,158,...,4.9,NaN,NaN,NaN,NaN,sys,04-JUN-21 01.14.57.048000000 PM,sys,04-JUN-21 01.12.22.839632000 PM,57

In [2]:
X = np.log(df[['PJCTJJ', 'SJZYL']])
X = sm.add_constant(X)
y = np.log(df['volume'])
model = sm.OLS(y, X)
result = model.fit()
print(result.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                 volume   R-squared:                       0.818
Model:                            OLS   Adj. R-squared:                  0.818
Method:                 Least Squares   F-statistic:                 1.114e+05
Date:                Thu, 27 Apr 2023   Prob (F-statistic):               0.00
Time:                        16:35:47   Log-Likelihood:                -19794.
No. Observations:               49427   AIC:                         3.959e+04
Df Residuals:                   49424   BIC:                         3.962e+04
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          6.7559      0.027    250.497      0.000       6.703       6.809
PJCTJJ        -0.7645      0.004   -173.529      0.000      -0.773      -0.756
SJZYL          0.4017      0.005     84.834      0.000       0.392       0.411
==============================================================================
Omnibus:                    37819.565   Durbin-Watson:                   1.994
Prob(Omnibus):                  0.000   Jarque-Bera (JB):          1460642.883
Skew:                          -3.333   Prob(JB):                         0.00
Kurtosis:                      28.784   Cond. No.                         93.2
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [3]:
import statsmodels.formula.api as smf

model = smf.ols('np.log(volume) ~ np.log(PJCTJJ) + np.log(SJZYL)', df)
result = model.fit()
print(result.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:         np.log(volume)   R-squared:                       0.818
Model:                            OLS   Adj. R-squared:                  0.818
Method:                 Least Squares   F-statistic:                 1.114e+05
Date:                Thu, 27 Apr 2023   Prob (F-statistic):               0.00
Time:                        16:35:47   Log-Likelihood:                -19794.
No. Observations:               49427   AIC:                         3.959e+04
Df Residuals:                   49424   BIC:                         3.962e+04
Df Model:                           2
Covariance Type:            nonrobust
==================================================================================
                     coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------
Intercept          6.7559      0.027    250.497      0.000       6.703       6.809
np.log(PJCTJJ)    -0.7645      0.004   -173.529      0.000      -0.773      -0.756
np.log(SJZYL)      0.4017      0.005     84.834      0.000       0.392       0.411
==============================================================================
Omnibus:                    37819.565   Durbin-Watson:                   1.994
Prob(Omnibus):                  0.000   Jarque-Bera (JB):          1460642.883
Skew:                          -3.333   Prob(JB):                         0.00
Kurtosis:                      28.784   Cond. No.                         93.2
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [4]:
df_test = pd.read_csv('./21年6月实时数据NJ-S122其林门_test.csv')
predict = result.predict(df_test[['PJCTJJ', 'SJZYL']])
predict = np.exp(predict)
predict

0       59.639013
1       59.239381
2       11.858608
3       10.296367
4       13.930281
          ...
5400    39.593466
5401    12.930395
5402    52.103221
5403    19.038541
5404     5.791330
Length: 5405, dtype: float64

In [5]:
predict.to_csv('pred.csv', index=False)